name: CI

on:
  release:
    types: [published]

  # pull_request:
  #   branches:
  #     - develop
  #     - master

jobs:
  upload-artifacts:
  steps:
    - uses: actions/checkout@v3
    - run: | 
      touch dictu-binary
    - uses: actions/upload-artifact@v3
      with:
        name: dictu-binary
        path: ./dictu-binary