on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  release:
    permissions:
      contents: write
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: Release
      uses: SierraSoftworks/gh-releases@v1.0.7
      with:
        overwrite: 'true'
        files: |
          Release.txt
