name: CI

on:
  release:
    types: [published]

  # pull_request:
  #   branches:
  #     - develop
  #     - master

jobs:
  upload-artifacts:
  steps:
  - uses: actions/checkout@v3
    run: |
      sudo apt update
      sudo apt-get install -y libcurl4-openssl-dev uuid-dev
      touch dictu-binary
  - uses: actions/upload-artifact@v3
    with:
      name: dictu-binary
      path: ./dictu-binary