# Publish GitHub workflow artifacts tutorial example
name: Publish GitHub Actions Artifacts Example

on:
  release:
    types: [published]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: step 1 - Compile binary
        run: |
          sudo apt update
          touch dictu
    
      - name: Step 2 - Upload binary
        uses: actions/upload-artifact@v3
        with: 
          name: assets-for-download
          path: dictu
