on:
  push:
    tags:
    - 'v*'

name: Upload Release Asset

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        echo ${{ github.sha }} > Release_${{ github.ref_name }}.txt
        echo "blah blah blah" > and_${{ github.ref_name }}_file
    - name: Test
      run: |
        cat Release_${{ github.ref_name }}.txt
    - name: Install nfpm
      run: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install nfpm
    - name: Release
      uses: SierraSoftworks/gh-releases@v1.0.7
      with:
        token: ${{ secrets.TOKEN }}
        overwrite: 'true'
        files: |
          Release_${{ github.ref_name }}.txt
          and_${{ github.ref_name }}_file
    - name: Package
      run: |
        nfpm -v


